image: node:14.18.0

before_script:
  - apt-get udpate -qq && apt-get install

cache:
  paths: 
    - node_modules/

stages:
  - build
  - test
  - deploy

build: 
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
  only:
    - default

test: 
  stage: test
  script: 
    - npm install
    - CI=true npm run test

deploy:
  stage: deploy
  image: ruby:latest
  script: 
    - npm i -g netlify-cli
    - npx netlify deploy --site https://talikasih.netlify.app/ --auth jqHEeTEH8pwaveuVcYYPB91pkbqHL7LFycw1g4cDfGY --prod
  dependencies:
    - build
  only :
  - default

