image: node:14.18.0


cache:
  paths: 
    - node_modules/

stages:
  - build
  - test
  - deploy

build: 
  stage: build
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules/
  only:
    - default

test: 
  stage: test
  script: 
    - yarn install
    - CI=true yarn run test

deploy:
  stage: deploy
  image: ruby:latest
  script: 
    - yarn add -g netlify-cli
    - npx netlify deploy --site https://talikasih.netlify.app/ --auth jqHEeTEH8pwaveuVcYYPB91pkbqHL7LFycw1g4cDfGY --prod
    dependencies:
    - build
  only :
  - default

