export const PROFILE_BEGIN = "PROFILE_BEGIN";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_FAIL = "PROFILE_FAIL";

export const PROFILE_UPDATE_BEGIN = "PROFILE_UPDATE_BEGIN";
export const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS";
export const PROFILE_UPDATE_FAIL = "PROFILE_UPDATE_FAIL";

export const GET_COMMENT_BEGIN = "GET_COMMENT_BEGIN";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_COMMENT_FAIL = "GET_COMMENT_FAIL";

export const GET_DETAIL_COMMENT_BEGIN = "GET_DETAIL_COMMENT_BEGIN";
export const GET_DETAIL_COMMENT_SUCCESS = "GET_DETAIL_COMMENT_SUCCESS";
export const GET_DETAIL_COMMENT_FAIL = "GET_DETAIL_COMMENT_FAIL";

export const POST_COMMENT_BEGIN = "POST_COMMENT_BEGIN";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const POST_COMMENT_FAIL = "POST_COMMENT_FAIL";