export const PROFILE_BEGIN = "PROFILE_BEGIN";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_FAIL = "PROFILE_FAIL";

export const PROFILE_UPDATE_BEGIN = "PROFILE_UPDATE_BEGIN";
export const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS";
export const PROFILE_UPDATE_FAIL = "PROFILE_UPDATE_FAIL";