const donateActionTypes = {
    BANK_TRANSFER_DONATE_START: 'BANK_TRANSFER_DONATE_START',
    BANK_TRANSFER_DONATE_SUCCESS: 'BANK_TRANSFER_DONATE_SUCCESS',
    BANK_TRANSFER_DONATE_FAILED: 'BANK_TRANSFER_DONATE_FAILED',
    CREDIT_CARD_DONATE_START: 'CREDIT_CARD_DONATE_START',
    CREDIT_CARD_DONATE_SUCCESS: 'CREDIT_CARD_DONATE_SUCCESS',
    CREDIT_CARD_DONATE_FAILED: 'CREDIT_CARD_DONATE_FAILED',
    DEBIT_CARD_DONATE_START: 'DEBIT_CARD_DONATE_START',
    DEBIT_CARD_DONATE_SUCCESS: 'DEBIT_CARD_DONATE_SUCCESS',
    DEBIT_CARD_DONATE_FAILED: 'DEBIT_CARD_DONATE_FAILED',
    ALL_DONATE_START: 'ALL_DONATE_START',
    ALL_DONATE_SUCCESS: 'ALL_DONATE_SUCCESS',
    ALL_DONATE_FAILED: 'ALL_DONATE_FAILED',
    DONATE_STATUS_START: 'DONATE_STATUS_START',
    DONATE_STATUS_SUCCESS: 'DONATE_STATUS_SUCCESS',
    DONATE_STATUS_FAILED: 'DONATE_STATUS_FAILED'
}

export default donateActionTypes;